# Generated by Django 4.1.3 on 2023-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='autor',
            field=models.IntegerField(blank=True, max_length=300, null=True),
        ),
    ]
